name: Bug Report
description: Report a bug or unexpected behavior in Cartographer
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command: `cartographer crawl --seeds https://example.com --out test.atls`
        2. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages, stack traces, or logs.
      render: shell
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Cartographer Version
      description: Run `cartographer version` or `cartographer --version`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version`
      placeholder: "v20.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/CentOS)
        - Windows (WSL)
        - Windows (Native)
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        If available, paste relevant log output from `--logFile` or stderr.
        **Tip:** Logs are in `./logs/crawl-<crawlId>.jsonl` if you used `--logFile`
      render: shell

  - type: textarea
    id: config
    attributes:
      label: CLI Command / Configuration
      description: What command did you run? Include all flags.
      placeholder: |
        cartographer crawl \
          --seeds https://example.com \
          --out test.atls \
          --mode prerender \
          --maxDepth 3 \
          --maxPages 100
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all requested information above
          required: true
        - label: I can reproduce this consistently
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem.
